#!/bin/bash

SHOWING=$(defaults read com.apple.finder CreateDesktop)

if [[ $SHOWING == false ]]; then
  defaults write com.apple.finder CreateDesktop true && killall Finder
  echo "Desktop now visible"
else
  defaults write com.apple.finder CreateDesktop false && killall Finder
  echo "Desktop hidden"
fi
